# Generated by Django 5.0.2 on 2024-09-26 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('noOfOwner', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phno', models.CharField(max_length=20)),
                ('bikeKm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/bikes/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('noOfOwner', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phno', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/cars/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('noOfOwner', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phno', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/pets/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
