# Generated by Django 5.0.2 on 2024-09-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
