# Generated by Django 5.0.2 on 2024-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_delete_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/bikes/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars/'),
        ),
    ]
