# Generated by Django 5.0.2 on 2024-09-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_bikes_image_alter_cars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/bikes/'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/bikes/'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/bikes/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars/'),
        ),
    ]
