# Generated by Django 5.0.2 on 2024-09-27 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_bikes_image1_bikes_image2_bikes_image3_cars_image1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/applications/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/applications/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/applications/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/applications/')),
                ('location', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phno', models.CharField(max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/mobiles/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/mobiles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/mobiles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/mobiles/')),
                ('location', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phno', models.CharField(max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
